pipeline{
    agent any
    stages {
        stage('Terraform-Init') {
            steps {
                echo 'initializing Terraform'
                sh 'terraform init'
            }           
        }
    }
    stage('Terraform Plan'){
        steps {
            script {
                echo 'terraform plan'
                sh 'terraform plan'
            }
        }
    }

    stage('Terraform Apply'){
        steps {
            script {
                echo 'Creating resources'
                sh 'terraform apply -auto-approve'
            }
        }
    }    
}
